spring.datasource.url=jdbc:postgresql://localhost:5432/growfinix_enquiry
spring.datasource.username=postgres
spring.datasource.password=janani14

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true